### ISSUE TITLE
When filtering someone by username who has a username that’s in others usernames, the person with the username inside their username will appear instead of the guy who had the original username

### ISSUE THREAD

**Issue by ColdlordXRepositories** [jeffalo/ocular#108]
**To Reproduce**
1. Go to 'Post search'
2. Click on 'By Username'
3. Put in a username that is included in another username
4. See broken posts

**Expected behavior**
It should show the person you typed in’s posts

**Screenshots**
Can’t add

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [safari]
 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXR]
 - Browser [e.g. safari]

**Comment by RedGuy12** [comment]
Sounds like a bug with ScratchDB, which is outside of Jeffalo's control.


________________________________
From: ColdlordXRepositories ***@***.***>
Sent: Friday, October 1, 2021 5:30:10 PM
To: jeffalo/ocular ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffalo/ocular] When filtering someone by username who has a username that’s in others usernames, the person with the username inside their username will appear instead of the guy who had the original username (#108)


To Reproduce
Steps to reproduce the behavior:

  1.  Go to 'Post search'
  2.  Click on 'By Username'
  3.  Put in a username that is included in another username
  4.  See broken posts

Expected behavior
It should show the person you typed in’s posts

Screenshots
Can’t add

Desktop (please complete the following information):

  *   OS: [iOS]
  *   Browser [safari]

Smartphone (please complete the following information):

  *   Device: [e.g. iPhoneXR]
  *   OS: [e.g. iOS8.1]
  *   Browser [e.g. safari]
  *   Version [e.g. 22]

**Comment by jeffalo** [comment]
redguy is right, this is something that only lefty can fix.
