### ISSUE TITLE
Make the forum post links for Scratch ones for ocular and make project links TurboWarp ones

### ISSUE THREAD

**Issue by Time-dragon** [jeffalo/ocular#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a Scratch post is linked and I can't access it due to many reasons.

**Describe the solution you'd like**
Link to Ocular post.

**Describe alternatives you've considered**
Copy-pasting the link into my search bar and then changing it to an Ocular link.

**Comment by jeffalo** [comment]
i don't plan on changing the content of posts. links should remain as is unless it's something weird like the youtube video pages which expect a /discuss/youtube route. 

you can always type the URLs manually.

**Comment by RedGuy12** [comment]
why can't you acess scratch?
________________________________
From: Toadbert ***@***.***>
Sent: Friday, June 25, 2021 1:50:21 PM
To: jeffalo/ocular ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffalo/ocular] Make the forum post links for Scratch ones for ocular (#87)


Is your feature request related to a problem? Please describe.
I'm always frustrated when a Scratch post is linked and I can't access it due to many reasons.

Describe the solution you'd like
Link to Ocular post.

Describe alternatives you've considered
Copy-pasting the link into my search bar and then changing it to an Ocular link.
