### ISSUE TITLE
url plus sign issues issues

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/ocular#9]
spaces turn into pluses in links and i look for link.

i dont really know whats going on here but heres a post https://scratch.mit.edu/discuss/post/4415347

edit:
when a link to ocular is shared on scratch, the plus signs (+) which are normally spaces are encoded to %2B, then when the link is clicked from scratch, ocular reads the %2B as a + and messes with the search query.

any ideas on how to fix this?

**Comment by JeffaloBob** [comment]
this can be seen if you send a link to the site on scratch (which is kinda their fault but since this is designed for scratch i should account for that)

https://jeffalo.net/projects/forums/?search=%2Btopic%3A343602+%2Busername%3Afdreerf&sort=relevance

becomes

https://jeffalo.net/projects/forums/?search=%2Btopic%3A343602%2B%2Busername%3Afdreerf&sort=relevance

**Comment by jeffalo** [comment]
fixed probably

**Comment by leahcimto** [comment]
why is this pinned

**Comment by jeffalo** [comment]
> why is this pinned

it used to be the biggest issue with the site
