### ISSUE TITLE
Sorry for being off-topic, but...

### ISSUE THREAD

**Issue by CodeGuy92** [jeffalo/ocular#93]
Did Paddle2See and ScratchCat actually set their own statuses, or did Jeffalo set them?

**Comment by FunctionalMetatable** [comment]
Why don't you ask Jeffalo on his profile? 
FYI:
CatsUnited set Paddle2See's status, because it was originally in the shefwerld json file
Jeffalo set ScratchCat's status, this can be seen in the JSON of the API response from https://my-ocular.jeffalo.net/api/user/ScratchCat
![image](https://user-images.githubusercontent.com/67440879/123691153-28970780-d84d-11eb-8bd5-a3115eb74243.png)

**Comment by jeffalo** [comment]
@FunctionalMetatable's answer is correct.
